baseurl = "https://yorodm.github.io/"
languageCode = "en-US"
title = "/home/yorodm"
theme = "hugo-theme-cactus-plus"
pluralizeListTitles = false
pygmentsCodeFences=true
pygmentsUseClasses=true
[params]
    enableRss = true
    name = "Yoandy Rodríguez Martínez"
    description = "Software, la vida y todo lo demás"
    bio = "Desarrollador, bloguero, amante de la música"
    # Enter optionally your twitter account
    twitter = "yorodm"
    enableRSS = true

    # Disqus comment
    disqusShortname = "home-yorodm"
    # Disable disqus comments by set `enableDisqus = "false"`
    enableDisqus = true

    # Duoshuo comment
    duoshuoShortname = "your_duoshuo_short_name"
    # Disable duoshuo comments by set `enableDuoshuo = "false"`
    enableDuoshuo = false

    enableGithubIssuesTips = false

    # Enable googleAnalytics
    enableGoogleAnalytics = false

    # Enable baiduAnalytics
    enableBaiduAnalytics = false
    # Baidu Tongji Code
    baiduAnalytics = 'your_baidu_tongji_code'

    # Add custom assets with their paths relative to the static folder
    customCSS = []
    customJS  = []

    # The variables below are optionally too and can be used to
    # translate or customize each string of the theme.

    # Navigation links
    archive = "archivo"
    about = "acerca de"
    tags = "etiquetas"
    home = "inicio"
    # Pagination links
    olderPosts = ""
    newerPosts = ""
    readMore = "más ..."
    # Sharing options and author information in posts
    aboutAuthor = "I am so interesting."
    tweet = ""
    share = ""


    # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
    iconFont = "font-awesome"
  # Add additional social link entries underneath

[social]
  twitter = "http://twitter.com/yorodm"
  github = "http://github.com/yorodm"
  stack-overflow = "http://stackoverflow.com/yorodm"