baseurl = "https://yorodm.github.io/"
languageCode = "en-US"
title = "/home/yorodm"
theme = "console"
pluralizeListTitles = false
pygmentsCodeFences=true
pygmentsUseClasses=true
[params]

  [[params.social]]
    name = "Twitter"
    url = "http://twitter.com/yorodm"
  [[params.social]]
    name = "GitHub"
    url = "http://github.com/yorodm"
  [[params.navlinks]]
    name = "about/"
    url = "about/"
  [[params.navlinks]]
    name = "blog/"
    url = "blog/"
  [[params.navlinks]]
    name = "series/"
    url = "series/"

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 50

  [[related.indices]]
    name = "series"
    weight = 100

[taxonomies]
    categories = "categories"
    tags = "tags"
    series = "series"
