baseurl = "https://yorodm.github.io/"
languageCode = "en-US"
title = "/home/yorodm"
theme = "hugo-theme-console"
pluralizeListTitles = false
pygmentsCodeFences=true
pygmentsUseClasses=true
[params]

  [[params.social]]
    name = "Twitter"
    url = "http://twitter.com/yorodm"
  [[params.social]]
    name = "GitHub"
    url = "http://github.com/yorodm"
  [[params.navlinks]]
    name = "about/"
    url = "about/"
  [[params.navlinks]]
  name = "blog/"
  url = "blog/"

[related]
  includeNewer = false
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "keywords"
    weight = 100

  [[related.indices]]
    name = "series"
    weight = 100
